/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_jiami_HelloWord */

#ifndef _Included_com_example_jiami_HelloWord
#define _Included_com_example_jiami_HelloWord
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_jiami_HelloWord
 * Method:    getString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_jiami_HelloWord_getString
  (JNIEnv *, jclass);

/*
 * Class:     com_example_jiami_HelloWord
 * Method:    add
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_example_jiami_HelloWord_add
  (JNIEnv *, jclass, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
